target-version = "py312"
line-length = 88

[lint]
ignore = [
    "B008",
    "ASYNC230",
    "BLE001",
    "DTZ005",
]

[lint.per-file-ignores]
"tests/**" = ["F811", "F841"]

[format]
quote-style = "double"
indent-style = "space"
